/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	char str[32];
	int choice;
	UartGets(str);
	sscanf(str, "%d", &choice);
	switch(choice){

	        case choice '1';
	     	   GPIOD->ODR |= BV(14);
		     	// delay 1000 ms
			    DelayMs(1000);
	    		break;

	        case choice_2;
			 // clear gpiod pin 14 -- Red LED OFF
			   GPIOD->ODR &= ~BV(14);
			   // delay 1000 ms
	           DelayMs(1000);
	            break;

        	case choice_3;
	            GPIOD->ODR |= BV(15);
				// delay 1000 ms
				DelayMs(1000);
				break;

        	case choice_4;
	       // clear gpiod pin 14 -- Red LED OFF
		     GPIOD->ODR &= ~BV(15);
	       	// delay 1000 ms
             DelayMs(1000);
             break;
	}

	return 0;
}


