/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "i2c_lcd.h"
#include "lis3dsh.h"
#include "spi.h"
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	int ret,x,y,z;
	LIS_Data val;
	SystemInit();
	ret = LcdInit();
	LIS_Init();
    DelayMs(1000);

    while(1)
    {
    	ret = LIS_DRdy();
    	if(ret)

	      {

    		if(x>0 && x<100)
		    sprintf(str, "X=%d, Y=%d \r\n", val.x, val.y);
			LcdPuts(LCD_LINE1,str);
		    sprintf(str, "Z=%d \r\n", val.z);
		    LcdPuts(LCD_LINE2,str);
			DelayMs(500);
		     if(y>=0 && y<=100)
		     val = LIS_GetData();
			 sprintf(str, "X=%d, Y=%d \r\n", val.x, val.y);
			 LcdPuts(LCD_LINE1,str);
	         sprintf(str, "Z=%d \r\n", val.z);
	         LcdPuts(LCD_LINE2,str);
			 DelayMs(500);
			if(z>=-100 && z<=100)
		    val = LIS_GetData();
    		sprintf(str, "X=%d, Y=%d \r\n", val.x, val.y);
    					 LcdPuts(LCD_LINE1,str);
    			         sprintf(str, "Z=%d \r\n", val.z);
    			         LcdPuts(LCD_LINE2,str);
    		             DelayMs(500);

	      }

    }



	return 0;
}
